import { Filter } from "@/custom";

export const filters: Filter[] = [
  {
    name: "color",
    label: "Color",
    type: "select",
    options: [
      "all",
      "black",
      "brown",
      "blue",
      "white",
      "grey",
      "pink",
      "beige",
      "red",
      "silver",
      "tan",
      "navy",
      "taupe",
      "green",
      "camel",
      "gold",
    ],
  },
  {
    name: "category",
    label: "Category",
    type: "select",
    options: [
      "all",
      "formal shoes",
      "men's shoes",
      "sneakers",
      "women's shoes",
      "loafers",
      "heels",
      "athletic shoes",
      "boots",
      "flats",
      "casual shoes",
      "sandals",
      "wedges",
      "slides",
      "mules",
      "slippers",
    ],
  },
  {
    name: "price",
    label: "Price",
    type: "range",
    range: { min: 0, max: 1000, step: 50 },
  },
];
